language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DEPLOY=false DEPLOY_DOCS=false COVERAGE=false TEST_DOCS=false JYTHON=false PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
matrix:
  include:
    - python: "2.7"
      env:
        - TEST_DOCS=true DEPLOY_DOCS=true PULL_REQUEST=$TRAVIS_PULL_REQUEST SCM_BRANCH=$TRAVIS_BRANCH
    - python: "3.4"
      env: TEST_DOCS=true
    - python: "2.7"
      env: COVERAGE=true
    - python: "2.7"
      env: JYTHON=true

before_install:
  - chmod +x ./.scripts/run_tests.sh
  - chmod +x ./.scripts/test_jython.sh
  - chmod +x ./.scripts/deploy_docs.sh
install:
  - pip install tox
script:
  - ./.scripts/run_tests.sh
  - if [ "$TEST_DOCS" == "true" ]; then tox -e docs; fi
  - ./.scripts/deploy_docs.sh
  - if [ "$COVERAGE" == "true" ]; then tox -e coverage; fi
  - ./.scripts/test_jython.sh;