language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION TEST_DOCS=false JYTHON=false COVERAGE=false DEPLOY_DOCS=false
matrix:
  include:
    # Tests and deploys docs
    - python: "2.7"
      env:
        - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION TEST_DOCS=true JYTHON=false COVERAGE=false DEPLOY_DOCS=true PULL_REQUEST=$TRAVIS_PULL_REQUEST SCM_BRANCH=$TRAVIS_BRANCH
    # Tests docs
    - python: "3.4"
      env: PYTHON_VERSION=$TRAVIS_PYTHON_VERSION TEST_DOCS=true JYTHON=false COVERAGE=false DEPLOY_DOCS=false
    # Runs coverage report
    - python: "2.7"
      env: PYTHON_VERSION=$TRAVIS_PYTHON_VERSION TEST_DOCS=false JYTHON=false COVERAGE=true DEPLOY_DOCS=false
    # Runs Jython tests
    - python: "2.7"
      env: PYTHON_VERSION=$TRAVIS_PYTHON_VERSION TEST_DOCS=false JYTHON=true COVERAGE=false DEPLOY_DOCS=false

before_install:
  - chmod +x ./.scripts/run_tests.sh
  - chmod +x ./.scripts/run_doc_tests.sh
  - chmod +x ./.scripts/run_coverage_tests.sh
  - chmod +x ./.scripts/test_jython.sh
  - chmod +x ./.scripts/deploy_docs.sh
install:
  - pip install tox
script:
  - ./.scripts/run_tests.sh
  - ./.scripts/run_doc_tests.sh
  - ./.scripts/run_coverage_tests.sh
  - ./.scripts/test_jython.sh;
after_success:
  - ./.scripts/deploy_docs.sh