language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
matrix:
  include:
    - python: "2.7"
      env: DOCS=true
    - python: "2.7"
      env: COVERAGE=true
    - python: "2.7"
      env: JYTHON=true

before_install:
  - chmod +x ./.scripts/run_tests.sh
  - chmod +x ./.scripts/test_jython.sh
install:
  - pip install tox
script:
  - ./.scripts/run_tests.sh
  - if [ ! -z "$DOCS" ]; then tox -e docs; fi
  - if [ ! -z "$COVERAGE" ]; then tox -e coverage; fi
  - if [ ! -z "$JYTHON" ]; then ./.scripts/test_jython.sh; fi